environment             = "production"
state_bucket            = "travelhub-terraform-state-590340239150"
github_repo_id          = "jd-sant/travelhub_miso"
branch_name             = "main"
frontend_github_repo_id = "jd-sant/travelhub_frontend"
